df <- read.csv('../../data/train.w.features.csv', header=TRUE, stringsAsFactors=TRUE)
head(df)
print(unique(df$Date))
store1 <- subset(df, Store==1)
store1
head(store1)
store1d1 <- subset(store1, Dept==1)
store1d1
require(ggplot2)
ggplot(store1d1, aes(x=Date, y=Weekly_Sales)) + geom_line()
ggplot(store1d1, aes(x=Date, y=Weekly_Sales)) + geom_line(aes(group=1)))
ggplot(store1d1, aes(x=Date, y=Weekly_Sales)) + geom_line(aes(group=1))
ggplot(store1d1, aes(x=reorder(Month,Date), y=Weekly_Sales)) + geom_line(aes(group=1))
ggplot(store1d1, aes(x=reorder(Month,Date), y=Weekly_Sales)) + geom_bar()
ggplot(store1d1, aes(x=reorder(Month,Date), y=Weekly_Sales)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=reorder(Date,Date), y=Weekly_Sales)) + geom_bar(stat="identity")
head(store1d1)
ggplot(store1d1, aes(x=reorder(IsHoliday,Date), y=Weekly_Sales)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=reorder(IsHoliday,Date), y=Weekly_Sales)) + geom_bar(stat="identity")
class(df$Date)
as.Date(df$Date)
store1d1$Date <- as.Date(store1d1$Date)
ggplot(store1d1, aes(x=reorder(IsHoliday,Date), y=Weekly_Sales)) + geom_bar(stat="identity")
store1d1.holidays <- subset(store1d1, IsHoliday==TRUE)
store1d1.holidays
ggplot(store1d1.holidays, aes(x=Date, y=Weekly_Sales)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=Date, y=Weekly_Sales)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity", colour="black")
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity") + scale_fill_manual(values=c("#999999", "#E69F00")
)
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity") + scale_fill_manual(values=c("#999999", "#E69F00"))
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity")
ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity") + scale_fill_manual(values=c("#999999", "#E69F00"))
plot <- ggplot(store1d1, aes(x=Date, y=Weekly_Sales, fill=IsHoliday)) + geom_bar(stat="identity") + scale_fill_manual(values=c("#999999", "#E69F00"))
plot
history()
history(reverse=TRUE)
history(file=analysis1.R)
history(file="analysis1.R")
savehistory(file="analysis1.R")
